### ISSUE TITLE
'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'

### ISSUE THREAD

**Issue by wm901115nwpu** [tensorlayer/openpose-plus#143]
AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'

**Comment by wm901115nwpu** [comment]
[TL] ERROR: file models/pose.npz doesn't exist.
2018-10-31 10:59:24.507394: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.507846: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.508547: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.510640: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.510984: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.511161: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.511516: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.511705: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.511320: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.512290: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.513057: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.513780: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.514702: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


Traceback (most recent call last):
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
2018-10-31 10:59:24.516588: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


    return fn(*args)
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
2018-10-31 10:59:24.517371: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.517793: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.518125: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.518294: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.518590: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


2018-10-31 10:59:24.518726: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


         [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_STRING], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_3"](convert_image, arg1)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,368,368,3], [?,46,46,57], [?,46,46,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
         [[Node: IteratorGetNext/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_245_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 467, in <module>
    single_train(dataset)
  File "train.py", line 251, in single_train
    sess.run([train_op, total_loss, stage_losses, l2_loss, last_conf, last_paf])
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'
Traceback (most recent call last):

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "train.py", line 143, in _data_aug_fn
    M_rotate = tl.prepro.affine_rotation_matrix(angle=(-30, 30))  # -40~40

  File "/home/wangmeng/anaconda3/lib/python3.6/site-packages/tensorlayer/lazy_imports.py", line 74, in __getattribute__
    return module.__getattribute__(x)

AttributeError: module 'tensorlayer.prepro' has no attribute 'affine_rotation_matrix'


         [[Node: PyFunc = PyFunc[Tin=[DT_FLOAT, DT_STRING], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_3"](convert_image, arg1)]]
         [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,368,368,3], [?,46,46,57], [?,46,46,1]], output_types=[DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
         [[Node: IteratorGetNext/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_245_IteratorGetNext", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
affine_rotation_matrix
