### ISSUE TITLE
Tensorflow Python loading error

### ISSUE THREAD

**Issue by vidursatija** [tensorlayer/openpose-plus#148]
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 7 and 3. Shapes are [7,7,128,128] and [3,3,128,128]. for 'Assig
n' (op: 'Assign') with input shapes: [7,7,128,128], [3,3,128,128].
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "example-inference-1.py", line 64, in <module>
    measure(main)
  File "/home/vidursatija/openpose-plus/openpose_plus/inference/common.py", line 198, in measure
    result = f()
  File "example-inference-1.py", line 60, in main
    inference(args.base_model, args.path_to_npz, args.data_format, image_files, args.plot)
  File "example-inference-1.py", line 25, in inference
    'create TfPoseEstimator')
  File "/home/vidursatija/openpose-plus/openpose_plus/inference/common.py", line 198, in measure
    result = f()
  File "example-inference-1.py", line 24, in <lambda>
    e = measure(lambda: TfPoseEstimator(path_to_npz, model_func, target_size=(width, height), data_format=data_format),
  File "/home/vidursatija/openpose-plus/openpose_plus/inference/estimator.py", line 25, in __init__
    self._warm_up(graph_path)
  File "/home/vidursatija/openpose-plus/openpose_plus/inference/estimator.py", line 30, in _warm_up
    tl.files.load_and_assign_npz_dict(graph_path, self.persistent_sess)
  File "/usr/local/lib/python3.5/dist-packages/tensorlayer/files/utils.py", line 1781, in load_and_assign_npz_dict
    ops.append(varlist[0].assign(params[key]))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 645, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/state_ops.py", line 216, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1731, in __init__
    control_input_ops)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1579, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 7 and 3. Shapes are [7,7,128,128] and [3,3,128,128]. for 'Assign' (op: 'Assign') with input shapes: [7,7,128,128]
, [3,3,128,128].
```

I'm getting the following error while running the following command
```
python3 example-inference-1.py --path-to-npz hao28-pose600000.npz --images pic3.jpg --base-model vgg
```

Model has been downloaded from tensorlayer's pretrained repo

**Comment by zsdonghao** [comment]
I think model is `vggtiny` rather than `vgg` ?

**Comment by vidursatija** [comment]
I tried vggtiny and mobilenet. The same type of error but for different variables

**Comment by vidursatija** [comment]
Can somebody help?

**Comment by mrkaworu** [comment]
You probably just need to use hao28_experimental as the --base-model parameter.

**Comment by zeroMrCc** [comment]
Is there anyone who has trained the model in your own machine, and get good result? Can you share your .npz file? I just want to see the performance of this model, but it takes a lot of time to train this model with the GPU GTX1060 in my machine.

**Comment by vidursatija** [comment]
Thank you so much @mrkaworu 
It is loading the parameters
