### ISSUE TITLE
How to select the GPU to use?

### ISSUE THREAD

**Issue by salvador-blanco** [tensorlayer/openpose-plus#178]
I am working in a machine with 4 GPU, I share the computer so  I should only use one GPU
Although the GPU 0 is not being used, I get an error when running training.py
I think it is related to the fact that I can not specify the GPU to be used 
```
[TL]   got  88: model/stage6/branch2/c4/kernel:0   (7, 7, 128, 128)
[TL]   got  89: model/stage6/branch2/c5/kernel:0   (7, 7, 128, 128)
[TL]   got  90: model/stage6/branch2/c6/kernel:0   (1, 1, 128, 128)
[TL]   got  91: model/stage6/branch2/pafs/kernel:0   (1, 1, 128, 38)
Start - n_step: 600000 batch_size: 8 lr_init: 4e-05 lr_decay_every_step: 136106
2019-02-27 11:34:07.926730: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-02-27 11:34:09.575398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:02:00.0
totalMemory: 10.92GiB freeMemory: 10.76GiB
2019-02-27 11:34:10.665607: E tensorflow/core/common_runtime/direct_session.cc:167] Internal: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 11721506816
Traceback (most recent call last):
  File "train.py", line 471, in <module>
    single_train(dataset)
  File "train.py", line 235, in single_train
    with tf.Session(config=config) as sess:
  File "/home/chava/.pyenv/versions/anaconda3-5.0.1/envs/OPoPLus/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1509, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/chava/.pyenv/versions/anaconda3-5.0.1/envs/OPoPLus/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 638, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/home/chava/.pyenv/versions/anaconda3-5.0.1/envs/OPoPLus/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session
```

**Comment by jovialio** [comment]
Just add this and select the gpu by number accordingly.

```
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"
```
