### ISSUE TITLE
inference1.py error

### ISSUE THREAD

**Issue by blue-butterfly** [tensorlayer/openpose-plus#181]

**Comment by blue-butterfly** [comment]
when I run the command :   CUDA_VISIBLE_DEVICES='2'  python3 examples/example-inference-1.py --path-to-npz models/pose30000.npz --base-model=vgg --images data/1.jpg --limit 1 

Traceback (most recent call last):
  File "examples/example-inference-1.py", line 64, in <module>
    measure(main)
  File "/export/sxy/code/openpose-plus/openpose_plus/inference/common.py", line 198, in measure
    result = f()
  File "examples/example-inference-1.py", line 60, in main
    inference(args.base_model, args.path_to_npz, args.data_format, image_files, args.plot)
  File "examples/example-inference-1.py", line 30, in inference
    humans, heatMap, pafMap = measure(lambda: e.inference(image), 'e.inference')
  File "/export/sxy/code/openpose-plus/openpose_plus/inference/common.py", line 198, in measure
    result = f()
  File "examples/example-inference-1.py", line 30, in <lambda>
    humans, heatMap, pafMap = measure(lambda: e.inference(image), 'e.inference')
  File "/export/sxy/code/openpose-plus/openpose_plus/inference/estimator.py", line 42, in inference
    humans, heatmap_up, pafmap_up = self.post_processor(heatmap[0], pafmap[0])
  File "/export/sxy/code/openpose-plus/openpose_plus/inference/post_process.py", line 151, in __call__
    humans = estimate_paf(peaks[0], heatmap[0], pafmap[0])
  File "/export/sxy/code/openpose-plus/openpose_plus/inference/post_process.py", line 85, in estimate_paf
    from .pafprocess import pafprocess  # TODO: don't depend on it
ModuleNotFoundError: No module named 'openpose_plus.inference.pafprocess'

**Comment by blue-butterfly** [comment]
Is there anyone help me?

**Comment by jovialio** [comment]
You will need to run this `./scripts/install-pafprocess.sh`

**Comment by blue-butterfly** [comment]
@jovialio  Thanks for your help.  But the link in install-pafprocess.sh is not found ?

**Comment by blue-butterfly** [comment]
@jovialio  Thanks for your help, I have done， thank you！！！！

**Comment by salvador-blanco** [comment]
@blue-butterfly @javialio how did you do it, I have the same problem `svn: not found` ??

**Comment by salvador-blanco** [comment]
I solved it by manually installing pafprocess from
https://github.com/ildoonet/tf-pose-estimation/tree/master/tf_pose/pafprocess
