### ISSUE TITLE
Training on gpu with cuda 10.0 and tensorflow-gpu

### ISSUE THREAD

**Issue by BadMachine** [tensorlayer/openpose-plus#223]
## PLATFORM: WIN10, tensorflow-gpu==1.13.2, tensorlayer==1.11.1, CUDA 10
Hello there!

3 days i cant run train.py.
The problem is my GPU compatable only with cuda 10.X
So, i tried to install tensorflow-gpu=1.13, when im tryin` to run train.py i get error:
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    import tensorlayer as tl
  File "E:\Anaconda3\lib\site-packages\tensorlayer\__init__.py", line 47, in <module>
    from tensorlayer import initializers
  File "E:\Anaconda3\lib\site-packages\tensorlayer\initializers.py", line 7, in <module>
    from tensorlayer.layers.core import LayersConfig
  File "E:\Anaconda3\lib\site-packages\tensorlayer\layers\__init__.py", line 12, in <module>
    from .activation import *
  File "E:\Anaconda3\lib\site-packages\tensorlayer\layers\activation.py", line 6, in <module>
    from tensorlayer.layers.core import Layer
  File "E:\Anaconda3\lib\site-packages\tensorlayer\layers\core.py", line 39, in <module>
    TF_GRAPHKEYS_VARIABLES = tf.GraphKeys.GLOBAL_VARIABLES
AttributeError: module 'tensorflow' has no attribute 'GraphKeys'

if i run the code with tensorflow==1.13.2 it goes ok, but strongly on CPU.

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
already uncommented
Can i force it to run on gpu?

**Comment by BadMachine** [comment]
I solve it.
So, the ultimate solution is:
https://github.com/tensorflow/tensorflow/issues/22794#issuecomment-468970045
Note, that u HAVE to use python 3.6 ONLY! Before install all dependencies with conda make sure that u deleted all tensorflow instances!

This solution especially useful for  everyone who have rtx nVidia series and tryin` to run this beautiful repo code on windows. Cheers!
