### ISSUE TITLE
Convert models that has BN layer to UFF format

### ISSUE THREAD

**Issue by lgarithm** [tensorlayer/openpose-plus#75]
* [x] support channel_first in BN (https://github.com/tensorlayer/tensorlayer/commit/4e6f768bd2d0c0f27c2385ce7f541b848deb7953)
* [x] Convert a model that has BN layer to UFF

**Comment by lgarithm** [comment]
```
INFO:tensorflow:Froze 227 variables.
INFO:tensorflow:Converted 227 variables to const ops.
Using output node outputs/conf
Using output node outputs/paf
Converting to UFF graph
Traceback (most recent call last):
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 84, in convert_tf2numpy_dtype
    return dtype.as_numpy_dtype
AttributeError: 'int' object has no attribute 'as_numpy_dtype'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./uff-runner.py", line 185, in <module>
    main()
  File "./uff-runner.py", line 163, in main
    uff_model = measure(lambda: uff.from_tensorflow(tf_model, output_names), 'uff.from_tensorflow')
  File "/home/lg/core/repos/github.com/tensorlayer/openpose-plus/inference/common.py", line 197, in measure
    result = f()
  File "./uff-runner.py", line 163, in <lambda>
    uff_model = measure(lambda: uff.from_tensorflow(tf_model, output_names), 'uff.from_tensorflow')
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 120, in from_tensorflow
    name="main")
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 76, in convert_tf2uff_graph
    uff_graph, input_replacements)
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 63, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes)
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 42, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter_functions.py", line 372, in convert_bias_add
    kwargs["tf_nodes"][biases_name])
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 121, in convert_tf2numpy_const_node
    np_dtype = cls.convert_tf2numpy_dtype(tf_node.attr['dtype'].type)
  File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py", line 95, in convert_tf2numpy_dtype
    return np.dtype(dt[dtype])
TypeError: data type "invalid" not understood
```

@zsdonghao

**Comment by zsdonghao** [comment]
Should we add `data_format` into [tf.nn.bias_add](https://www.tensorflow.org/api_docs/python/tf/nn/bias_add)

**Comment by lgarithm** [comment]
The bug is in `convert_bias_add` of `converter_functions.py` 
(File "/usr/lib/python3.5/dist-packages/uff/converters/tensorflow/converter_functions.py", line 372, in convert_bias_add)

It assumes the `b` in `tf.nn.bias_add(x, b)` is always a constant.

```python

@tf2uff.register(["BiasAdd"])
def convert_bias_add(name, tf_node, inputs, uff_graph, **kwargs):
    fmt = convert_to_str(tf_node.attr['data_format'].s)
    fmt = fmt if fmt else "NHWC"
    biases_name = inputs[1]
    biases_array = tf2uff.convert_tf2numpy_const_node(
        kwargs["tf_nodes"][biases_name])
    inputs = inputs[:1]
    if fmt == 'NCHW':
        ndim = 4
        new_shape = [-1] + [1] * (ndim - 2)
        biases_array = biases_array.reshape(new_shape)
    uff_graph.const(biases_array, biases_name)
    uff_graph.binary(inputs[0], biases_name, 'add', name)
    return [tf2uff.split_node_name_and_output(inp)[0] for inp in inputs]

```

Fix should be simple, just follow one of its correct implementation:

```python3
@tf2uff.register(["Add"])
def convert_add(name, tf_node, inputs, uff_graph, **kwargs):
    uff_graph.binary(inputs[0], inputs[1], 'add', name)
    return [tf2uff.split_node_name_and_output(inp)[0] for inp in inputs]
```

**Comment by lgarithm** [comment]
Shall be fixed in https://github.com/tensorlayer/tensorlayer/pull/849

**Comment by lgarithm** [comment]
Command to install TL from a branch:

```bash
pip install https://github.com/tensorlayer/tensorlayer/archive/bn.zip
```

**Comment by lgarithm** [comment]
@DEKHTIARJonathan we had two problems here:

1. `tf.nn.batch_normalization` doesn't support customized `data_format`, it uses `channel_last` by default, but `channel_first` is required in tensorRT

2. tensorRT has bug in supporting `tf.bias_add`, that's why I re-implemented `tf.bias_add` with `tf.add` in tollowing way:

```python
def _to_channel_first_bias(b):
    """Reshape [c] to [c, 1, 1]."""
    channel_size = int(b.shape[0])
    new_shape = (channel_size, 1, 1)
    # new_shape = [-1, 1, 1]  # doesn't work with tensorRT
    return tf.reshape(b, new_shape)

def _bias_add(x, b, data_format):
    """Alternative implementation of tf.nn.bias_add which is compatiable with tensorRT."""
    if data_format == 'NHWC':
        return tf.add(x, b)
    elif data_format == 'NCHW':
        return tf.add(x, _to_channel_first_bias(b))
    else:
        raise ValueError('invalid data_format: %s' % data_format)
```

To reproduce the 2nd one, use the code in my previous comment https://github.com/tensorlayer/openpose-plus/issues/75#issuecomment-423645128

**Comment by lgarithm** [comment]
@luomai
